<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultados [
<!ELEMENT resultados (resultado*)>
    <!ELEMENT resultado (equipoLocal, golesLocal, equipoVisitante, golesVisitante)>
        <!ELEMENT equipoLocal (#PCDATA)>
        <!ELEMENT golesLocal (#PCDATA)>
        <!ELEMENT equipoVisitante (#PCDATA)>
        <!ELEMENT golesLocal (#PCDATA)>
]>

<resultados>
    <resultado>
        <equipoLocal>Nottingham Presa</equipoLocal>
        <golesLocal>0</golesLocal>
        <equipoVisitante>Inter de Mitente</equipoVisitante>
        <golesVisitante>1</golesVisitante>
    </resultado>
    <resultado>
        <equipoLocal>Vodka Juniors</equipoLocal>
        <golesLocal>3</golesLocal>
        <equipoVisitante>Sparta da Risa</equipoVisitante>
        <golesVisitante>3</golesVisitante>
    </resultado>
    <resultado>
        <equipoLocal>Water de Munich</equipoLocal>
        <golesLocal>4</golesLocal>
        <equipoVisitante>Esteaua es del grifo</equipoVisitante>
        <golesVisitante>2</golesVisitante>
    </resultado>
</resultados>